[project]
name = "openai-company-agent"
version = "0.1.3"
description = "openai-company-agent"
authors = [{ name = "Eusebiu Jecan", email = "eusebiu.jecan@uipath.com" }]
dependencies = [
    "uipath-openai-agents>=0.0.1",
    "openai>=1.0.0",
    "uipath-dev>=0.0.15",
]
requires-python = ">=3.11"


