[project]
name = "agent-as-tools"
version = "0.1.0"
description = "Language routing agent example using OpenAI Agents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "uipath-openai-agents>=0.1.0, <0.2.0",
    "openai-agents>=0.6.5",
    "uipath>=2.4.10",
]

[dependency-groups]
dev = [
    "uipath-dev>=0.0.8",
]

[tool.uv.sources]
uipath-openai-agents = { path = "../..", editable = true }
